FROM python:3.6.6
RUN mkdir -p /usr/src/blogapp
WORKDIR /usr/src/blogapp
COPY pip.conf /root/.pip/pip.conf
COPY requirements.txt /usr/src/blogapp/
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
EXPOSE 8002
RUN pip install -r requirements.txt
RUN rm -rf /usr/src/blogapp
COPY . /usr/src/blogapp
CMD ["python","./manage.py","runserver","0.0.0.0:8002"]